# Generated by Django 3.1.5 on 2021-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210706_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default/user.png', upload_to='users/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_status',
            field=models.CharField(choices=[('unassigned', 'unassigned'), ('assigned', 'assigned')], default='unassigned', max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Admitted', 'Admitted'), ('Discharged', 'Discharged'), ('Outpatient', 'Outpatient')], default='Registered', max_length=250),
        ),
    ]
