# Generated by Django 3.2.5 on 2021-07-12 19:00

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210712_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=50)),
                ('program_description', ckeditor.fields.RichTextField()),
                ('program_date_creation', models.DateTimeField(auto_now=True)),
                ('program_duration', models.TimeField()),
                ('doctor_available', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_clinic_program', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='labtechnician',
            name='user',
        ),
        migrations.RemoveField(
            model_name='nurse',
            name='user',
        ),
        migrations.RemoveField(
            model_name='reception',
            name='user',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lab_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_lab', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presciption',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_prescription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
        migrations.DeleteModel(
            name='LabTechnician',
        ),
        migrations.DeleteModel(
            name='Nurse',
        ),
        migrations.DeleteModel(
            name='Reception',
        ),
    ]
