# Generated by Django 3.2.5 on 2021-07-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
