# Generated by Django 3.2.5 on 2021-07-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_account_is_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_patient',
        ),
    ]
