# Generated by Django 3.2.5 on 2021-07-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_patient_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='note',
        ),
    ]
